### PR TITLE
fix: play nicley with hyprdots

### PR DESCRIPTION
**Pull request by rubiin**
Uses hyprdots screenshot.sh and rofilauncher.sh for application search. Also tweaks fonts and spacing

### CODE REVIEW

**Comment by rubiin** [comment]
This setting file is a reference and totally optional.

**Comment by rubiin** [comment]
@kRHYME7 hyprpanel uses ags and has osd, bar , and inbuilt notification service .
On hyprdots, it uses waybar,dunst and (swayosd) optionally. We should also add on readme how to disable them 

https://hyprpanel.com/getting_started/hyprpanel.html#what-does-it-do-differently

**Comment by rubiin** [comment]
image

Currently you get this

**Comment by kRHYME7** [comment]
@rubiin  😭 sorry for forgetting about this PR.  Can we still get it back? I don't know why I don't get those recent notifs. My bad really.

**Comment by rubiin** [comment]
Yeah. I just closed this as there are many changes and will most likely do a new PR if you like.
Will probably have to wait till these get merged.
The bar looks 70-80% like old waybar 

https://github.com/Jas-SinghFSU/HyprPanel/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aopen+author%3Arubiin

**Pull request closed without merging**
